name: Sprint Bot
on:
  schedule:
    - cron: '0 1 * * *' # Chạy vào 8:00 sáng VN (1:00 UTC) mỗi ngày
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run bot
        run: |
          pip install requests
          python app.py
